spring.application.name=voting-system
#app.dynamodb.endpoint=${DYNAMODB_ENDPOINT}
#app.dynamodb.region=${AWS_REGION:us-east-1}
#app.dynamodb.table-name=${DYNAMODB_TABLE:voting-system}
#app.dynamodb.access-key=${AWS_ACCESS_KEY_ID:test}
#app.dynamodb.secret-key=${AWS_SECRET_ACCESS_KEY:test}
