spring.application.name=voting-system
springdoc.swagger-ui.url=/openapi.yaml
aws.sqs.vote-system-queue-url=${VOTE_SYSTEM_QUEUE_URL:http://localhost:4566/000000000000/vote-system}
aws.sqs.endpoint=${AWS_ENDPOINT:http://localhost:4566}
aws.sqs.region=${AWS_REGION:us-east-1}
aws.sqs.access-key-id=${AWS_ACCESS_KEY_ID:test}
aws.sqs.secret-access-key=${AWS_SECRET_ACCESS_KEY:test}
aws.dynamodb.endpoint=${AWS_ENDPOINT:http://localhost:4566}
aws.dynamodb.region=${AWS_REGION:us-east-1}
aws.dynamodb.access-key-id=${AWS_ACCESS_KEY_ID:test}
aws.dynamodb.secret-access-key=${AWS_SECRET_ACCESS_KEY:test}

